ALTER TABLE USERS DROP CONSTRAINT FK_USERS_ROLEID
ALTER TABLE MAINMENUVALUE DROP CONSTRAINT MAINMENUVALUE_ROLEID
ALTER TABLE MAINMENUVALUE DROP CONSTRAINT MINMENUVALUEMAINMENUID
ALTER TABLE SUBMENU DROP CONSTRAINT FK_SUBMENU_MAINMENUID
ALTER TABLE SUBMENUVALUE DROP CONSTRAINT SBMNUVALUEMNMNUVALUEID
ALTER TABLE SUBMENUVALUE DROP CONSTRAINT SUBMENUVALUE_SUBMENUID
ALTER TABLE MENUITEM DROP CONSTRAINT FK_MENUITEM_SUBMENUID
ALTER TABLE MENUITEMVALUE DROP CONSTRAINT MNTEMVALUESBMNUVALUEID
ALTER TABLE MENUITEMVALUE DROP CONSTRAINT MNUITEMVALUEMENUITEMID
ALTER TABLE PACKAGE_UNIT_RELATION DROP CONSTRAINT PCKAGEUNITRELATIONRLID
ALTER TABLE FACILITY DROP CONSTRAINT FK_FACILITY_UNITID
ALTER TABLE LABTESTS DROP CONSTRAINT LBTSTSLBTESTCATEGORYID
DROP INDEX USERS_FK_USERS_ROLEID
DROP TABLE USERS
DROP TABLE USER_ROLE
DROP TABLE MAINMENU
DROP INDEX MNMNVLUEMNMNVLUEROLEID
DROP INDEX MNMNVLMNMNVLMAINMENUID
DROP TABLE MAINMENUVALUE
DROP INDEX SBMNFKSBMENUMAINMENUID
DROP TABLE SUBMENU
DROP INDEX SBMNVLSBMNVLMNMNVLUEID
DROP INDEX SBMNVLSBMNVLESUBMENUID
DROP TABLE SUBMENUVALUE
DROP INDEX MNTEMFKMNITEMSUBMENUID
DROP TABLE MENUITEM
DROP INDEX MNTMVLMNTMVLSBMNVLUEID
DROP INDEX MNTMVLMNTMVLMENUITEMID
DROP TABLE MENUITEMVALUE
DROP TABLE PACKAGING_UNIT
DROP TABLE BRAND
DROP TABLE GENERIC
DROP TABLE LAB_TEST_CATEGORY
DROP INDEX PCKGNTRLTPCKGNTRLTNRLD
DROP TABLE PACKAGE_UNIT_RELATION
DROP TABLE SPECIALIST
DROP TABLE UNITS
DROP INDEX FCLITYFKFACILITYUNITID
DROP TABLE FACILITY
DROP TABLE ROOM_CLASS
DROP TABLE RELATIONS
DROP INDEX LBTSTLBTSTSLBTSTCTGRYD
DROP TABLE LABTESTS
DELETE FROM ID_GEN WHERE GEN_NAME = 'MENUITEM_GEN'
DELETE FROM ID_GEN WHERE GEN_NAME = 'UNIT_GEN'
DELETE FROM ID_GEN WHERE GEN_NAME = 'LABTESTS_GEN'
DELETE FROM ID_GEN WHERE GEN_NAME = 'LABCATEGORY_GEN'
DELETE FROM ID_GEN WHERE GEN_NAME = 'BRAND_GEN'
DELETE FROM ID_GEN WHERE GEN_NAME = 'RELATION_GEN'
DELETE FROM ID_GEN WHERE GEN_NAME = 'USERS_GEN'
DELETE FROM ID_GEN WHERE GEN_NAME = 'SUBMENU_GEN'
DELETE FROM ID_GEN WHERE GEN_NAME = 'MAINMENU_GEN'
DELETE FROM ID_GEN WHERE GEN_NAME = 'PACKAGINGUNIT_GEN'
DELETE FROM ID_GEN WHERE GEN_NAME = 'GENERIC_GEN'
DELETE FROM ID_GEN WHERE GEN_NAME = 'FACILITY_GEN'
DELETE FROM ID_GEN WHERE GEN_NAME = 'SPECIALIST_GEN'
DELETE FROM ID_GEN WHERE GEN_NAME = 'ROOM_CLASS_GEN'
DELETE FROM ID_GEN WHERE GEN_NAME = 'SUBMENUVALUE_GEN'
DELETE FROM ID_GEN WHERE GEN_NAME = 'MAINMENUVALUE_GEN'
DELETE FROM ID_GEN WHERE GEN_NAME = 'ROLE_GEN'
DELETE FROM ID_GEN WHERE GEN_NAME = 'MENUITEMVALUE_GEN'
