DROP TABLE SETUP


CREATE TABLE [dbo].[SETUP](
	[VARIABLE] [varchar](50) NOT NULL,
	[VALUE] [varchar](50) NOT NULL,
	[VERSION] [int] NULL
) ON [PRIMARY]

INSERT INTO SETUP VALUES ('BRANCH_ID','',1)
INSERT INTO SETUP VALUES ('BUDGETEDATE','30-09-2022',1)
INSERT INTO SETUP VALUES ('BUDGETSDATE','01-10-2021',1)
INSERT INTO SETUP VALUES ('BUDSMTH','10',1)
INSERT INTO SETUP VALUES ('DEPARTMENT_STATUS','TRUE',1)
INSERT INTO SETUP VALUES ('HO','001',1)
INSERT INTO SETUP VALUES ('HOMECURRENCY_ID','',1)
INSERT INTO SETUP VALUES ('IBS','ASH',1)
INSERT INTO SETUP VALUES ('MULTI_CURRENCY','FALSE',1)
INSERT INTO SETUP VALUES ('BACKDATE','01-10-2020',1)



INSERT INTO SETUP VALUES ('BRANCH_ID','',1)
